version: '3.8'

services:
  apache:
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - lamp-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: lamp_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lamp-network

networks:
  lamp-network:
    driver: bridge

volumes:
  db_data:
